feedback_log:
- date: '2025-12-04'
  items: []
- date: '2025-12-05'
  items:
  - action: want_more
    title: 关于 Open AI 代号 Garlic（大蒜🧄）的模型 Chris 说不会在近期推出 他们下周会发
  - action: want_more
    title: Gemini 3 这真是神操作 简单文本 prompt 就能生成一个网站，还能用手跟 3D 模型互动
  - action: want_more
    title: Google 🍌 Nano Banana 家族包揽 LMArena 图像编辑领域前三名： 1⃣Nan
  - action: want_more
    title: Next.js/React 爆出 CVSS 10.0 满分漏洞！ ⚠️ 所有使用 App Route
  - action: want_more
    title: 随手分享小技巧如何让你的命令行也支持指纹 Mac 很多时候我们用命令行工具执行系统动作时候，都需要手
  - action: want_more
    title: 明年真是个大年，主要的几个头部的AI公司都准备IPO。 之前OpenAI说要准备IPO，国内的智谱和
  - action: want_more
    title: 'RT Toby Wang: Referenced @dotey''s prompt using Nan'
- date: '2025-12-07'
  items:
  - action: want_more
    title: 构建高效的生产级上下文感知多智能体框架 Google 官方这篇博客深入探讨了在开发复杂的 AI 智能
  - action: want_more
    title: 'RT Shelly: 年度 review，写给我们团队的话：技术的源头是星辰大海，但赚钱的入口在“信'
  - action: want_more
    title: 🍌 nano banana pro prompt Use this prompt to genera
  - action: want_more
    title: This is a really good report on the reality of bui
  - action: want_more
    title: 期待看到更多有趣的、有价值的应用诞生。 Let’s build something real.
- date: '2025-12-11'
  items:
  - action: want_more
    title: 阿里千问公测才23天，月活用户就突破3000万。 更猛的是，刚宣布完这个数字，就把AI PPT、AI
  - action: want_more
    title: Cursor 效能实战：这家 290 亿美元巨头如何用 AI 自动解决 80% 的内部支持需求 Cu
  - action: want_more
    title: Agentic AI Foundation — advancing open-source agen
  - action: want_more
    title: 1) chatgpt summarizes insights about you into 1 li
- date: '2025-12-10'
  items:
  - action: want_more
    title: 目前觉得还不错的读AI论文方式分享： 1. 原始论文PDF放在左屏幕。 用系统自带或任意分屏工具，比
  - action: want_more
    title: Github涨星最好的办法就是分享提示词，哈哈哈。 邪修啊！ 不过Nano Banana pro确实
  - action: want_more
    title: 速度提升 4 倍、精度比肩 Claude Code：深度解读 @relace_ai 的「代码检索新架
- date: '2025-12-15'
  items:
  - action: want_more
    title: 主流 AI 应用如何处理「记忆」？ · ChatGPT：全量注入与轻量摘要 - 更贴心的伙伴 · C
  - action: want_more
    title: 'RT Stometa: 开始玩推特三个月了。这周跑了625次测试，发现了个问题。 背景是这样的： 做'
  - action: not_interested
    title: 今天在国家天文台拍的星空延时摄影，里面应该有不少流星，冻麻了
  - action: not_interested
    title: 补一张流星
  - action: want_more
    title: Skills are all you need!
  - action: want_more
    title: 2026年软件工程师求职生存指南 2023年那套成为软件工程师的方法，到了2026年将不再适用。 随
learned_preferences:
  additional_interests: []
  additional_filters: []
  source_adjustments: {}
  keyword_adjustments:
    prompt: 4
    google: 2
    nano: 2
    banana: 3
    this: 2
    you: 2
statistics:
  total_feedback_count: 25
  liked_count: 23
  disliked_count: 2
  last_updated: '2026-02-24T02:00:27.948240'
